insert into demo.Cohort (description) values	('Mass. General Hospital');
insert into demo.Cohort (description) values	('Florida Hospital');
insert into demo.Cohort (description) values	('New York-Presbyterian Hospital');
insert into demo.Cohort (description) values 	('Jackson Memorial Hospital');
insert into demo.Cohort (description) values 	('University of Pittsburgh Medical Center');
insert into demo.Cohort (description) values 	('Montefiore Medical Center');
insert into demo.Cohort (description) values 	('The Cleveland Clinic');
insert into demo.Cohort (description) values 	('Methodist University Hospital');
insert into demo.Cohort (description) values 	('Barnes-Jewish Hospital');
insert into demo.Cohort (description) values 	('The Mount Sinai Medical Center');
insert into demo.Cohort (description) values 	('Norton Hospital');
insert into demo.Cohort (description) values 	('Erie County Medical Center');
insert into demo.Cohort (description) values 	('Memorial Hermann Southwest Hospital');
insert into demo.Cohort (description) values 	('UAB Hospital');
insert into demo.Cohort (description) values 	('Christiana Hospital');
insert into demo.Cohort (description) values 	('Beaumont Hospital');
insert into demo.Cohort (description) values 	('Spectrum Health Butterworth Hospital');
insert into demo.Cohort (description) values 	('Memorial Regional Hospital');
insert into demo.Cohort (description) values 	('Bergen Regional Medical Center');
insert into demo.Cohort (description) values 	('Beth Israel Medical Center');
insert into demo.Cohort (description) values 	('Ohio State University Hospital');
insert into demo.Cohort (description) values 	('Brookdale University Hospital and Medical Center');
insert into demo.Cohort (description) values 	('Dignity Health - California Hospital Med. Ctr.');
insert into demo.Cohort (description) values 	('Twin Cities Community Hospital');
insert into demo.Cohort (description) values 	('San Leandro Hospital');
